projects:
  SSTeMM_Mobile_App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: 6323hynkvvaj7ajlhdr32m3yhy
        maxDepth: 2
extensions:
  amplify:
    version: 3
